seed_everything: 2969591811

data:
    class_path: clip_graph.data.gassodatamodule.PubmedGraphDataModule
    init_args:
        data_dir: 'data/pubmed'
        seed: ${seed_everything}
        num_workers: -1
        pin_memory: true
        batch_size: 1
# ckpt_path: lightning_logs/gnn-pretrain/pubmed/version_3/checkpoints/epoch=19-step=20.ckpt
model:
    class_path: clip_graph.gassolit.LitGAE
    init_args:
        node_features_keys:
            - 'graph_x'

        # we do this rather than jsonargparse class_path etc so that the
        # Lightning object can save its hyperparameters and have them be small
        # string and integer things rather than huge binary model objects
        model_class_name: 'GassoSpace'
        model_params:
            in_channels: 768  # input feature vector dims, inductive or transductive
            out_channels: 768
            # this goes with transductive_identity_features above: if that's
            # set to true, the idea is that each node's feature is just its
            # index, and we learn an arbitrary embedding for each node in the
            # first layer of the graph model, in which case we have to tell it
            # how many nodes there are in the whole graph
            # num_nodes: 8721  # only usable if transductive

            hidden_channels: 64
            num_layers: 3
            dropout: 0.3
            training: true
            ops: ['gat', 'gcn', 'gin', 'sage', 'linear']
            # ops: ['gat']

        lr: 1.0e-2
        weight_decay: 0.0
        eps: 1.0e-6
        betas:
            - 0.9
            - 0.999

trainer:
    enable_checkpointing: true
    callbacks:
        - class_path: pytorch_lightning.callbacks.LearningRateMonitor

        - class_path: pytorch_lightning.callbacks.DeviceStatsMonitor

        - class_path: pytorch_lightning.callbacks.early_stopping.EarlyStopping
          init_args:
              monitor: 'val_auc'
              mode: 'max'
              patience: 3
              strict: true
              check_finite: true
              min_delta: 0.01

    #
    # Hardware
    #

    num_nodes: 1
    accelerator: 'gpu'
    devices: 1

    precision: 16

    #
    # Logging
    #

    log_every_n_steps: 1  # one step is one epoch
    # track_grad_norm: 2  # the 2-norm
    enable_model_summary: true
    enable_progress_bar: true

    logger:
        class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
        init_args:
            save_dir: 'lightning_logs/gnn-pretrain/'
            name: 'pubmed'
            default_hp_metric: false
            log_graph: false

    #
    # Debugging features
    #

    deterministic: false  # scatter_add_cuda_kernel has no deterministic implementation
    detect_anomaly: false

    #
    # Limits on epochs/steps/batches/time
    #

    max_epochs: 100
    min_epochs: 20

    limit_train_batches: 1
    limit_val_batches: 1
    limit_test_batches: 1
    limit_predict_batches: 1

    gradient_clip_val: 1
    gradient_clip_algorithm: 'norm'
